FROM golang:1.25.1-alpine3.22

WORKDIR /backend

RUN apk add --no-cache make
RUN apk add --no-cache bash curl && curl -1sLf \
  'https://dl.cloudsmith.io/public/infisical/infisical-cli/setup.alpine.sh' | bash \
  && apk add infisical

RUN go install github.com/air-verse/air@latest
COPY .air.toml .

COPY go.mod go.sum ./

